<?php
namespace HttpService;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


class HttpServiceProcessor {
  protected $handler_ = null;
  public function __construct($handler) {
    $this->handler_ = $handler;
  }

  public function process($input, $output) {
    $rseqid = 0;
    $fname = null;
    $mtype = 0;

    $input->readMessageBegin($fname, $mtype, $rseqid);
    $methodname = 'process_'.$fname;
    if (!method_exists($this, $methodname)) {
      $input->skip(TType::STRUCT);
      $input->readMessageEnd();
      $x = new TApplicationException('Function '.$fname.' not implemented.', TApplicationException::UNKNOWN_METHOD);
      $output->writeMessageBegin($fname, TMessageType::EXCEPTION, $rseqid);
      $x->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
      return;
    }
    $this->$methodname($rseqid, $input, $output);
    return true;
  }

  protected function process_uRegister($seqid, $input, $output) {
    $args = new \HttpService\HttpService_uRegister_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \HttpService\HttpService_uRegister_result();
    try {
      $result->success = $this->handler_->uRegister($args->name, $args->phoneNumber, $args->email, $args->password);
    } catch (\HttpService\AuthException $error) {
      $result->error = $error;
    }
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'uRegister', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('uRegister', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
  protected function process_uLogin($seqid, $input, $output) {
    $args = new \HttpService\HttpService_uLogin_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \HttpService\HttpService_uLogin_result();
    try {
      $result->success = $this->handler_->uLogin($args->phoneNumber, $args->password);
    } catch (\HttpService\AuthException $error) {
      $result->error = $error;
    }
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'uLogin', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('uLogin', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
  protected function process_logout($seqid, $input, $output) {
    $args = new \HttpService\HttpService_logout_args();
    $args->read($input);
    $input->readMessageEnd();
    $this->handler_->logout($args->id);
    return;
  }
  protected function process_getUsersId($seqid, $input, $output) {
    $args = new \HttpService\HttpService_getUsersId_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \HttpService\HttpService_getUsersId_result();
    $result->success = $this->handler_->getUsersId();
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'getUsersId', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('getUsersId', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
  protected function process_getLogs($seqid, $input, $output) {
    $args = new \HttpService\HttpService_getLogs_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \HttpService\HttpService_getLogs_result();
    $result->success = $this->handler_->getLogs($args->timestamp);
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'getLogs', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('getLogs', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
}
