<?php
namespace HttpService;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface HttpServiceIf {
  /**
   * @param string $name
   * @param string $phoneNumber
   * @param string $email
   * @param string $password
   * @return \HttpService\User
   * @throws \HttpService\AuthException
   */
  public function uRegister($name, $phoneNumber, $email, $password);
  /**
   * @param string $phoneNumber
   * @param string $password
   * @return \HttpService\User
   * @throws \HttpService\AuthException
   */
  public function uLogin($phoneNumber, $password);
  /**
   * @param int $id
   */
  public function logout($id);
  /**
   * @return int[]
   */
  public function getUsersId();
  /**
   * @param int $timestamp
   * @return array
   */
  public function getLogs($timestamp);
}


