/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DataService_CONSTANTS_H
#define DataService_CONSTANTS_H

#include "DataService_types.h"

namespace DataService {

class DataServiceConstants {
 public:
  DataServiceConstants();

  int32_t INT32CONSTANT;
  std::map<std::string, std::string>  MAPCONSTANT;
};

extern const DataServiceConstants g_DataService_constants;

} // namespace

#endif
