/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "HttpService_constants.h"



const HttpServiceConstants g_HttpService_constants;

HttpServiceConstants::HttpServiceConstants() {
}



