/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HttpService_CONSTANTS_H
#define HttpService_CONSTANTS_H

#include "HttpService_types.h"



class HttpServiceConstants {
 public:
  HttpServiceConstants();

};

extern const HttpServiceConstants g_HttpService_constants;



#endif
